version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/third_party" # Location of package manifests
    schedule:
      interval: "daily"
    # Disable version updates for pip dependencies,
    # only required security updates 
    open-pull-requests-limit: 0
    groups:
      pip:
        applies-to: security-updates
        patterns:
          - "*"