# Runs bandit security checker for code written in Python.
name: Bandit

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux:
    name: Bandit
    runs-on: ubuntu-latest
  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Clone the git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install pip packages
        run: pip install -r third_party/requirements.txt

      # Scan is run only for the 'tools' folder.
      - name: Run Bandit
        run: |
          bandit -r tools
