#
# Copyright (C) 2023 Intel Corporation
#
# Part of the Unified-Runtime Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.TXT
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
name: coverity-unified-runtime
# It runs static analysis build - Coverity. It requires special token (set in CI's secret).

on: [push, pull_request]
#on:
#  workflow_dispatch:
#  schedule:
#    # Run every day at 23:00 UTC
#    - cron: '0 23 * * *'

env:
  WORKDIR:                           ${{ github.workspace }}
  COVERITY_SCAN_NOTIFICATION_EMAIL:  ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
  COVERITY_SCAN_TOKEN:               ${{ secrets.COVERITY_SCAN_TOKEN }}
  COVERITY_SCAN_PROJECT_NAME:        ${{ github.repository }}
  COVERITY_SCAN_BUILD_COMMAND:       "cmake --build ${{github.workspace}}/build"
  COVERITY_SCAN_BRANCH_PATTERN:      "main"
  TRAVIS_BRANCH:                     ${{ github.ref_name }}


permissions:
  contents: read

jobs:
  linux:
    name: Coverity
    runs-on: coverity

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Clone the git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install pip packages
        run: pip install -r third_party/requirements.txt

      - name: Configure CMake
        run: >
          cmake
          -B $WORKDIR/build
          -DUR_ENABLE_TRACING=ON
          -DUR_DEVELOPER_MODE=ON
          -DUR_BUILD_TESTS=ON
          -DUMF_ENABLE_POOL_TRACKING=ON
          -DUR_FORMAT_CPP_STYLE=ON
          -DCMAKE_BUILD_TYPE=Debug
          -DUR_BUILD_ADAPTER_L0=ON
          -DUR_BUILD_ADAPTER_OPENCL=ON
          -DUR_BUILD_ADAPTER_CUDA=ON
          -DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so
          -DUR_BUILD_ADAPTER_NATIVE_CPU=ON
          -DUR_BUILD_ADAPTER_HIP=ON

      - name: Run Coverity
        run: |
          cd $WORKDIR/build
          wget https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh
          patch < "../.github/scripts/0001-travis-fix-travisci_build_coverity_scan.sh.patch"
          bash ./travisci_build_coverity_scan.sh
