name: E2E Cuda

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e-build-hw:
    # trigger only if PR comment contains "e2e-cuda"
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/e2e-cuda') }}
    name: Start e2e job
    # use core flow, run it with cuda specific parameters
    uses: ./.github/workflows/e2e_core.yml
    # parameters that we pass to the core flow
    with:
      name: "CUDA"
      runner_tag: "CUDA_E2E"
      str_name: "cuda"
      prefix: "ext_oneapi_"
      config: "--cuda"
      unit: "gpu"
