name: E2E Cuda

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  e2e-build-hw:
    if: ${{ contains(github.event.head_commit.message, 'test-e2e') }}
    name: Start e2e job
    #uses: ./.github/workflows/e2e_core.yml
    #with:
    #  name: "CUDA"
    #  runner_tag: "CUDA_E2E"
    #  str_name: "cuda"
    #  prefix: "ext_oneapi_"
    #  config: "--cuda"
    #  unit: "gpu"
    
    runs-on: 'ubuntu-22.04'
    steps:
    - name: TEST
      run: |
        echo "YYY ${{github.event.head_commit.message}}"

