---
name: Deploy weekly prerelease

on:
  schedule:
    # At 23:00 on Friday, GitHub actions schedule is in UTC time.
    - cron: 0 23 * * 5

permissions:
  contents: read

jobs:
  weekly-prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Create weekly prerelease
        run:
          gh release create --prerelease --title "Weekly Stable Snapshot $(date +%Y/%m/%d)" weekly-$(date +%Y-%m-%d)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
